### ISSUE TITLE
Gamestrap UI

### ISSUE THREAD

**Issue by rodrigod89** [Bloodyaugust/missilewarunity#1]
Hey @Bloodyaugust ,
I'm the owner of Gamestrap UI and I noticed you had the asset in this project.

Although I like seeing people using the asset and I know you didn't mean harm but could you make the repository private or remove Gamestrap UI completely from the repository?

Remember that the older commits will still contain the asset so you would have to sanitize it and if you still need the asset you can ignore the folder so it doesn't end up public and easily searchable.

For more information on how you can use the asset take a look at the Unity's ASSET STORE TERMS OF SERVICE AND EULA https://unity3d.com/legal/as_terms

I hope you understand and thanks for using Gamestrap UI!

**Comment by Bloodyaugust** [comment]
This is now fixed, for all committed versions. Feel free to ping me if you have any other worries.
